### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by jmesnil** [jmesnil/wildfly-charts-old#9]
This requires:
* 1 `service` to for the `https` port (`8443`)
* 1 `route` to the `https` service
* access to a Java keystore from a secret

One caveat is that the configuration for HTTPS varies between S2I (as described in https://github.com/wildfly/wildfly-cekit-modules/blob/master/jboss/container/wildfly/launch/https/module.yaml) and bootable jar (as illustrated in https://github.com/wildfly-extras/wildfly-jar-maven-plugin/blob/cf431c188ffb6d8523ccd8f52f554a0bd1cef776/examples/https/pom.xml#L46).

The chart should not try to unify the 2 deployment alternatives but must ensure that both are possible.

In any case, both would need some common configs, e.g.

```yaml
deploy:
  https:
    enabled: true # triggers the creation of the service and route for HTTPS
    secret: <name of the secret containing the keystore> # the absence of this secret would fail installing the chart
```

The bootable-jar does not need anything else as all values will be passed in a CLI script from the application's pom.xml (e.g. https://github.com/wildfly-extras/wildfly-jar-maven-plugin/blob/master/examples/scripts/https.cli) at build time.

The S2I mechanism would need additional en vars that can be provided by regular `deploy.env` items:

```yaml
deploy:
  env:
    - name: HTTPS_KEYSTORE_TYPE
      value: JKS
    - name: HTTPS_KEYSTORE_DIR
      value: <path where the secret is mounted>
    - name: HTTPS_KEYSTORE
       value: <key of the secret containing the key store>
   - name: HTTPS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: <key of the secret that contains the password to access the keystore>
          name: <name of the secret>
 ```

This is an example and may not be accurate
